[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "celery -A backend.app.tasks.celery_app beat --loglevel=info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
